In [1]:
import yfinance as yf
import pandas as pd

In [17]:
tickers = ['IBM','MSFT','AAPL']

In [18]:
data = yf.download(tickers, period = '1mo', group_by='ticker')

[*********************100%***********************]  3 of 3 completed

In [19]:
data

                                 AAPL                                      \
                                 Open        High         Low       Close
Date
2023-01-03 00:00:00-05:00  130.279999  130.899994  124.169998  125.070000
2023-01-04 00:00:00-05:00  126.889999  128.660004  125.080002  126.360001
2023-01-05 00:00:00-05:00  127.129997  127.769997  124.760002  125.019997
2023-01-06 00:00:00-05:00  126.010002  130.289993  124.889999  129.619995
2023-01-09 00:00:00-05:00  130.470001  133.410004  129.889999  130.149994
2023-01-10 00:00:00-05:00  130.259995  131.259995  128.119995  130.729996
2023-01-11 00:00:00-05:00  131.250000  133.509995  130.460007  133.490005
2023-01-12 00:00:00-05:00  133.880005  134.259995  131.440002  133.410004
2023-01-13 00:00:00-05:00  132.029999  134.919998  131.660004  134.759995
2023-01-17 00:00:00-05:00  134.830002  137.289993  134.130005  135.940002
2023-01-18 00:00:00-05:00  136.820007  138.610001  135.029999  135.210007
2023-01-19 00:00:00-05:00  134.080002  136.250000  133.770004  135.270004
2023-01-20 00:00:00-05:00  135.279999  138.020004  134.220001  137.869995
2023-01-23 00:00:00-05:00  138.119995  143.320007  137.899994  141.110001
2023-01-24 00:00:00-05:00  140.309998  143.160004  140.300003  142.529999
2023-01-25 00:00:00-05:00  140.889999  142.429993  138.809998  141.860001
2023-01-26 00:00:00-05:00  143.169998  144.250000  141.899994  143.960007
2023-01-27 00:00:00-05:00  143.160004  147.229996  143.080002  145.929993
2023-01-30 00:00:00-05:00  144.960007  145.550003  142.850006  143.000000
2023-01-31 00:00:00-05:00  142.699997  144.339996  142.279999  144.289993

                                                        MSFT              \
                            Adj Close     Volume        Open        High
Date
2023-01-03 00:00:00-05:00  125.070000  112117500  243.080002  245.750000
2023-01-04 00:00:00-05:00  126.360001   89113600  232.279999  232.869995
2023-01-05 00:00:00-05:00  125.019997   80962700  227.199997  227.550003
2023-01-06 00:00:00-05:00  129.619995   87686600  223.000000  225.759995
2023-01-09 00:00:00-05:00  130.149994   70790800  226.449997  231.240005
2023-01-10 00:00:00-05:00  130.729996   63896200  227.759995  231.309998
2023-01-11 00:00:00-05:00  133.490005   69458900  231.289993  235.949997
2023-01-12 00:00:00-05:00  133.410004   71379600  235.259995  239.899994
2023-01-13 00:00:00-05:00  134.759995   57758000  237.000000  239.369995
2023-01-17 00:00:00-05:00  135.940002   63646600  237.970001  240.910004
2023-01-18 00:00:00-05:00  135.210007   69672800  241.570007  242.380005
2023-01-19 00:00:00-05:00  135.270004   58280400  233.779999  235.520004
2023-01-20 00:00:00-05:00  137.869995   79972200  234.860001  240.740005
2023-01-23 00:00:00-05:00  141.110001   81760300  241.100006  245.169998
2023-01-24 00:00:00-05:00  142.529999   66435100  242.500000  243.949997
2023-01-25 00:00:00-05:00  141.860001   65799300  234.479996  243.300003
2023-01-26 00:00:00-05:00  143.960007   54105100  243.649994  248.309998
2023-01-27 00:00:00-05:00  145.929993   70492800  248.990005  249.830002
2023-01-30 00:00:00-05:00  143.000000   64015300  244.509995  245.600006
2023-01-31 00:00:00-05:00  144.289993   60339047  243.449997  247.949997

                                                                         \
                                  Low       Close   Adj Close    Volume
Date
2023-01-03 00:00:00-05:00  237.399994  239.580002  239.580002  25740000
2023-01-04 00:00:00-05:00  225.960007  229.100006  229.100006  50623400
2023-01-05 00:00:00-05:00  221.759995  222.309998  222.309998  39585600
2023-01-06 00:00:00-05:00  219.350006  224.929993  224.929993  43597700
2023-01-09 00:00:00-05:00  226.410004  227.119995  227.119995  27369800
2023-01-10 00:00:00-05:00  227.330002  228.850006  228.850006  27033900
2023-01-11 00:00:00-05:00  231.110001  235.770004  235.770004  28669300
2023-01-12 00:00:00-05:00  233.559998  238.509995  238.509995  27269500
2023-01-13 00:00:00-05:00  234.919998  239.229996  239.229996  21317700
2023-01-17 00:00:00-05:00  237.089996  240.350006  240.350006  29831300
2023-01-18 00:00:00-05:00  235.520004  235.809998  235.809998  30028700
2023-01-19 00:00:00-05:00  230.679993  231.929993  231.929993  28623000
2023-01-20 00:00:00-05:00  234.509995  240.220001  240.220001  35323400
2023-01-23 00:00:00-05:00  239.649994  242.580002  242.580002  31934000
2023-01-24 00:00:00-05:00  240.440002  242.039993  242.039993  40234400
2023-01-25 00:00:00-05:00  230.899994  240.610001  240.610001  66526600
2023-01-26 00:00:00-05:00  242.000000  248.000000  248.000000  33454500
2023-01-27 00:00:00-05:00  246.830002  248.160004  248.160004  26480800
2023-01-30 00:00:00-05:00  242.199997  242.710007  242.710007  25867400
2023-01-31 00:00:00-05:00  242.945007  247.809998  247.809998  26541072

                                  IBM                                      \
                                 Open        High         Low       Close
Date
2023-01-03 00:00:00-05:00  141.100006  141.899994  140.479996  141.550003
2023-01-04 00:00:00-05:00  142.070007  143.619995  141.369995  142.600006
2023-01-05 00:00:00-05:00  142.440002  142.500000  140.009995  141.110001
2023-01-06 00:00:00-05:00  142.380005  144.250000  141.580002  143.699997
2023-01-09 00:00:00-05:00  144.080002  145.470001  143.399994  143.550003
2023-01-10 00:00:00-05:00  143.610001  144.850006  142.899994  144.800003
2023-01-11 00:00:00-05:00  145.000000  145.529999  143.449997  145.259995
2023-01-12 00:00:00-05:00  144.880005  146.660004  144.520004  145.550003
2023-01-13 00:00:00-05:00  144.059998  146.100006  144.009995  145.889999
2023-01-17 00:00:00-05:00  146.419998  147.179993  145.009995  145.190002
2023-01-18 00:00:00-05:00  144.399994  144.679993  140.229996  140.410004
2023-01-19 00:00:00-05:00  140.000000  142.229996  139.750000  140.619995
2023-01-20 00:00:00-05:00  141.669998  141.860001  140.509995  141.199997
2023-01-23 00:00:00-05:00  141.399994  142.990005  141.059998  141.860001
2023-01-24 00:00:00-05:00  141.250000  142.750000  140.000000  141.490005
2023-01-25 00:00:00-05:00  140.470001  141.029999  139.360001  140.759995
2023-01-26 00:00:00-05:00  137.529999  138.270004  132.979996  134.449997
2023-01-27 00:00:00-05:00  134.440002  135.490005  133.770004  134.389999
2023-01-30 00:00:00-05:00  134.320007  136.110001  133.979996  135.300003
2023-01-31 00:00:00-05:00  135.500000  135.649994  133.759995  134.729996


                            Adj Close    Volume
Date
2023-01-03 00:00:00-05:00  141.550003   3338600
2023-01-04 00:00:00-05:00  142.600006   3869200
2023-01-05 00:00:00-05:00  141.110001   2866600
2023-01-06 00:00:00-05:00  143.699997   3573600
2023-01-09 00:00:00-05:00  143.550003   3987700
2023-01-10 00:00:00-05:00  144.800003   2152100
2023-01-11 00:00:00-05:00  145.259995   3268700
2023-01-12 00:00:00-05:00  145.550003   2715900
2023-01-13 00:00:00-05:00  145.889999   2455700
2023-01-17 00:00:00-05:00  145.190002   2986500
2023-01-18 00:00:00-05:00  140.410004   6445600
2023-01-19 00:00:00-05:00  140.619995   4833900
2023-01-20 00:00:00-05:00  141.199997   7152700
2023-01-23 00:00:00-05:00  141.860001   5898400
2023-01-24 00:00:00-05:00  141.490005   4407600
2023-01-25 00:00:00-05:00  140.759995   7347500
2023-01-26 00:00:00-05:00  134.449997  17548500
2023-01-27 00:00:00-05:00  134.389999   8140700
2023-01-30 00:00:00-05:00  135.300003   5375700
2023-01-31 00:00:00-05:00  134.729996   7167783

In [20]:
data.to_csv('stock.csv')

In [25]:
data2 = yf.download(tickers, start = '2021-1-3', end = '2021-12-31', group_by='ticker')

[*********************100%***********************]  3 of 3 completed

In [27]:
data2.head()

                                 AAPL                                      \
                                 Open        High         Low       Close
Date
2021-01-04 00:00:00-05:00  133.520004  133.610001  126.760002  129.410004
2021-01-05 00:00:00-05:00  128.889999  131.740005  128.429993  131.009995
2021-01-06 00:00:00-05:00  127.720001  131.050003  126.379997  126.599998
2021-01-07 00:00:00-05:00  128.360001  131.630005  127.860001  130.919998
2021-01-08 00:00:00-05:00  132.429993  132.630005  130.229996  132.050003

                                                        MSFT              \
                            Adj Close     Volume        Open        High
Date
2021-01-04 00:00:00-05:00  127.874954  143301900  222.529999  223.000000
2021-01-05 00:00:00-05:00  129.455994   97664900  217.259995  218.520004
2021-01-06 00:00:00-05:00  125.098267  155088000  212.169998  216.490005
2021-01-07 00:00:00-05:00  129.367020  109578200  214.039993  219.339996
2021-01-08 00:00:00-05:00  130.483658  105158200  218.679993  220.580002

                                                                         \
                                  Low       Close   Adj Close    Volume
Date
2021-01-04 00:00:00-05:00  214.809998  217.690002  213.876373  37130100
2021-01-05 00:00:00-05:00  215.699997  217.899994  214.082687  23823000
2021-01-06 00:00:00-05:00  211.940002  212.250000  208.531647  35930700
2021-01-07 00:00:00-05:00  213.710007  218.289993  214.465851  27694500
2021-01-08 00:00:00-05:00  217.029999  219.619995  215.772568  22956200

                                  IBM                                      \
                                 Open        High         Low       Close
Date
2021-01-04 00:00:00-05:00  120.315491  120.382408  117.629066  118.489487
2021-01-05 00:00:00-05:00  119.512428  121.108986  119.130020  120.592735
2021-01-06 00:00:00-05:00  121.319313  126.080307  121.147224  123.604210
2021-01-07 00:00:00-05:00  124.321220  124.722755  122.619499  123.317398
2021-01-08 00:00:00-05:00  122.915871  123.632889  121.395790  122.877632


                            Adj Close   Volume
Date
2021-01-04 00:00:00-05:00  107.482880  5417443
2021-01-05 00:00:00-05:00  109.390755  6395872
2021-01-06 00:00:00-05:00  112.122490  8322708
2021-01-07 00:00:00-05:00  111.862328  4714740
2021-01-08 00:00:00-05:00  111.463409  4891305